### ISSUE TITLE
Hawkular Metrics User guide - Outdated information

### ISSUE THREAD

**Issue by theute** [hawkular/hawkular.github.io#200]
Querying with raw data seems outdated here: (/gauge/raw vs /stats)
http://www.hawkular.org/hawkular-metrics/docs/user-guide/#_raw_data

**Comment by theute** [comment]
Maybe not, getting confused as the server doesn't answer what I am expecting

**Comment by theute** [comment]
False alarm, sorry... (typo)

**Comment by jsanda** [comment]
No problem, but the user guide is actually out of date :)
