### ISSUE TITLE
Make the `master` branch as default (with the code) and `pages` as the branch with the built html

### ISSUE THREAD

**Issue by jkremser** [hawkular/hawkular.github.io#216]
This wasn't possible before this feature had been added https://github.com/blog/2228-simpler-github-pages-publishing

**Comment by theute** [comment]
It seems slightly different: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

Looks like `pages` branch should be named `gh-pages` (or have a directory explicitly named `docs` in the master branch)

**Comment by jkremser** [comment]
right, it wasn't obvious from the blog post. But in the help it says:

`If your site is a User or Organization Page that has a repository named <username>.github.io or <orgname>.github.io, you cannot publish your site's source files from different locations`

This is our case. For the "Organization Pages", the content is served only from the master.
